/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.NewsShortData

import com.squareup.moshi.Json

/**
 * 
 *
 * @param news 
 */


data class NewsShortDataList (

    @Json(name = "news")
    val news: kotlin.collections.List<NewsShortData>

)

