/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param testId 
 * @param passed 
 */


data class TestResults (

    @Json(name = "testId")
    val testId: kotlin.Int,

    @Json(name = "passed")
    val passed: kotlin.Boolean

)

