/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.NewsCategory

import com.squareup.moshi.Json

/**
 * 
 *
 * @param email 
 * @param name 
 * @param id 
 * @param interests 
 * @param birthdate 
 * @param avatarurl 
 */


data class UserData (

    @Json(name = "email")
    val email: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "interests")
    val interests: kotlin.collections.List<NewsCategory>,

    @Json(name = "birthdate")
    val birthdate: kotlin.String? = null,

    @Json(name = "avatarurl")
    val avatarurl: kotlin.String? = null

)

