/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param futureTests 
 * @param passedTests 
 * @param id 
 * @param userId 
 * @param score 
 */


data class UserTestsData (

    @Json(name = "futureTests")
    val futureTests: kotlin.collections.List<kotlin.Int>,

    @Json(name = "passedTests")
    val passedTests: kotlin.collections.List<kotlin.Int>,

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "userId")
    val userId: kotlin.Int,

    @Json(name = "score")
    val score: kotlin.Int

)

