/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param email 
 * @param password 
 * @param name 
 * @param birthdate 
 */


data class UserMailRegisterData (

    @Json(name = "email")
    val email: kotlin.String,

    @Json(name = "password")
    val password: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "birthdate")
    val birthdate: kotlin.String

)

